import type { ArticleAudience } from "./types";

/** Аудитория статей базы знаний по slug. */
export const articleAudienceBySlug: Record<string, ArticleAudience[]> = {
  "glavnaya-lenta-obyavleniy": ["brand", "creator", "manager"],
  chat: ["brand", "creator", "agency", "manager"],
  izbrannoe: ["brand", "creator", "manager"],
  otkliki: ["brand", "creator", "manager"],
  "moi-obyavleniya": ["brand", "creator", "manager"],
  dashbord: ["brand", "agency", "manager", "prime"],
  "moi-zadachi": ["brand", "creator", "agency", "manager", "prime"],
  kalendar: ["brand", "agency", "manager", "prime"],
  "poisk-ispolniteley-i-brendov": ["brand", "creator", "agency", "manager", "prime"],
  publikacii: ["brand", "agency", "manager", "prime"],
  arhiv: ["brand", "agency", "manager", "prime"],
  shablony: ["brand", "agency", "manager", "prime"],
  profil: ["brand", "creator", "agency", "manager"],
  nastroyki: ["brand", "creator", "agency", "manager"],
  obyavlenie: ["brand", "creator", "manager"],
  zadacha: ["brand", "creator", "agency", "manager", "prime"],
  "sozdanie-obyavleniya": ["brand", "agency", "manager"],
  "vhod-i-email": ["brand", "creator", "agency", "manager"],
  "kak-brendu-opublikovat-pervoe-obyavlenie": ["brand", "manager"],
  "kak-nayti-zakaz-i-otkliknutsya": ["creator"],
  "kak-menedzheru-nachat-rabotu": ["manager", "agency"],
  "statusy-zadachi": ["brand", "creator", "agency", "manager", "prime"],
  "roli-komandy": ["brand", "agency", "manager"],
  "chto-otkryvaet-prime": ["brand", "agency", "manager", "prime"],
  "nikssens-kak-pwa": ["brand", "creator", "agency", "manager"],
};
